In [2]:
#Assignment-1, Que-1

In [ ]:
#Printing Hello World

In [3]:
print("Hello World!")

Hello World!


In [4]:
#Assignment-1, Que-2

In [11]:
def Arithmetic_operations(a,b,operater): # giving two inputs and operater
    result = 0
    if operater == "+": 
        result = a+b      #Addition
    elif operater == "-":
        result = a-b      #Subtraction
    elif operater == "*":
        result = a*b      #Multiplication
    elif operater == "/":
        result = a/b      #Division
    elif operater == "%":
        result = a%b      #Giving remender
    else:
        result = str("invalid")   #if operater is not in 5 operaters we want, converting into string as we assign result as interger
    return result   #Returning value of function
#converting string into no. as in python variable automatically come as string, so operands should be no.
#calling function and passing the variable to fun
#Printing Result
print(Arithmetic_operations(int(input("Enter your first no.")), int(input("Enter second no.")), input("Enter operater")))


Enter your first no.4
Enter second no.6
Enter operater*
24


In [ ]:
#Assignment-1, Que-3

In [12]:
def factorial(num): #passing the variable to Factorail fun
    count = 1       #assigning the variable to run loop
    result =1       #assigning the variable to store result
    while count <= num:
        result = result*count
        count += 1              #incresing the variable 1 every time loop run
    return result               #Returning the result to fun call
#calling the fun and asking input from user
#printing result
print(factorial(int(input("Print Your no."))))   

Print Your no.5
120


In [13]:
#Assignment-1, Que-4

In [16]:
def Prime_numbers(num1, num2): #prime function for range
    a = num1
    while a <= num2:           #Checking every variable in range
        prime(a)               #calling function of every variable inside range
        a += 1
    return

def prime(num):               #prime function for range
    b = 2
    while b < num :           #Checking every variable from 2 to num-1, whether it is divisible or not
        if num % b == 0:      #if divisible then not prime, break the loop
            break
        b += 1
    if b == num:             #if no. not divisible upto num-1 then it is prime, check condition
        print(str(num) + " is prime")
    return
#Calling the fun and asking input range
Prime_numbers(int(input("Enter first no.")), int(input("Enter Second no.")))

Enter first no.3
Enter Second no.13
3 is prime
5 is prime
7 is prime
11 is prime
13 is prime


In [17]:
#Assignment-1, Que-5

In [19]:
def gcd(a,b):           #GCD FUNCTION
    if a==0:
        return b
    return gcd(b%a,a)   #Returning GCD value to lcm function

def lcm(num1, num2):    #LCM Function
    result = (num1 / gcd(num1, num2))*num2   #LCM logic
    return result                            #Returning value

#calling fun and asking user to give to input for LCM
print(lcm(int(input("Enter first no.")), int(input("Enter Second no."))))

Enter first no.12
Enter Second no.18
36.0


In [ ]:
#Assignment-1, Que-6

In [21]:
List = [3,5,4,6,1,4,8,7,6,9,76,54,4,3,6]  #Assigning a list of 15 no., can be multiple no.
n = len(List)                             
for i in range(n-1):                      #for loop intreted for 0 to 14
    for j in range(n-i-1):                #nested for loop intreted for 0 to 14-i, as every time range reduced by 1
        if List[j] <= List[j + 1]:        #because we get lowest term at every time in last reaminings
            swap = List[j]                #assign a swap variable for easy access of swapping
            List[j] = List[j + 1]
            List[j + 1] = swap

print(List)

[76, 54, 9, 8, 7, 6, 6, 6, 5, 4, 4, 4, 3, 3, 1]


In [1]:
#Assignment-1, Que-7

In [3]:
import numpy as np                               #Import numpy

a = np.array([3,5,4,6,1,4,8,7,6,9,76,54,4,3,6])  #Assigning a list of 15 no., can be multiple no.

n = len(a)
for i in range(n-1):                             #for loop intreted for 0 to 14
    for j in range(n-i-1):                       #nested for loop intreted for 0 to 14-i, as every time range reduced by 1
        if a[j] >= a[j + 1]:                     #because we get Highest term at every time in last reaminings
            swap = a[j]                          #assign a swap variable for easy access of swapping
            a[j] = a[j + 1]
            a[j + 1] = swap

print(a)

[ 1  3  3  4  4  4  5  6  6  6  7  8  9 54 76]


In [5]:
#Assignment-1, Que-8

In [ ]:
#This program took a lot of time for logic, I am a newcomer so I am trying to pick only logic from google (like reshape, random)
#and doing all programming by myself

In [6]:
import numpy as np                               # import numpy
import random                                    # import random to assign random variable to matrix

def Matrix(m,n):                                 # I am having problem in assigning order of 2D array as we assign in C like a[10]
    a = np.arange(m*n).reshape(m,n)              # I tried a lot, in end I assign value by arrange fun and then replace their value
    for i in range(m):                           # as random by using random.randit fun after by using for loop, 
        for j in range(n):                       # Memory wise and time wise may be it will take more time but I tried my logic
            a[i][j] = random.randint(-2, 5)
    return a


print(Matrix(int(input("Enter your rows")),int(input("Enter your column"))))

Enter your rows4
Enter your column5
[[ 3  3 -2  3 -2]
 [ 2  2  5  2  1]
 [ 2  1  2  2  3]
 [ 3  1  5  4 -2]]


In [8]:
#Assignment-1, Que-9, 

In [ ]:
#best program

In [13]:

import numpy as np                              # import numpy
import random                                   # import random to assign random variable to matrix

def Matrix(m ,n):                               # used previous que. method for two matrix
    a = np.arange( m *n).reshape(m ,n)          # want to give two matrix shape input by user and also want random value inside
    for i in range(m):
        for j in range(n):
            a[i][j] = random.randint(-2, 5)
    return a

def Matrix_multi(M1 ,M2):                      # define matrix multiplication function
    (a,b) = M1.shape                           # define shape to check whether multiplication is possible or not
    (c,d) = M2.shape
    if b == c :
        print("Matrix Multiplication is possible")
        M3 = np.arange(a*d).reshape(a,d)
        for i in range(a):                     
            for j in range(d):
                for k in range(b):
                    M3[i][j] = M1[i][k] * M2[k][j]
        print("Matrix Multiplication ")
        print(M3)
    else:
        print("Matrix Multiplication is not possible")
    return



M1 = Matrix(int(input("Enter first matrix rows")) ,int(input("Enter first matrix column")))     
print("First Matrix is")                                                                      #want to show matrix as value
print(M1)                                                                                     #given random      
M2 = Matrix(int(input("Enter second matrix rows")) ,int(input("Enter second matrix column")))      
print("Second Matrix is")                                                                      #want to show matrix as value
print(M2)                                                                                     #given random
Matrix_multi(M1,M2)

#want to check result with inbuilt multiplication but for that M1 & M2 should be of same shape


Enter first matrix rows3
Enter first matrix column4
First Matrix is
[[ 4 -1 -1  4]
 [ 3  4 -1  2]
 [ 1  3  0 -2]]
Enter second matrix rows4
Enter second matrix column3
Second Matrix is
[[ 2  5 -1]
 [ 3  4  4]
 [-2  5  5]
 [ 1  3  3]]
Matrix Multiplication is possible
Matrix Multiplication 
[[ 4 12 12]
 [ 2  6  6]
 [-2 -6 -6]]


In [ ]:
#Assignment-1, Que-10